#try to recreate encrypted file to see if the key that we think it is, is indeed the key.
#if it is, using the decipher flag will give us text that makes sense
vig -d JIBBS sdhama.hard.in 
vig -d JIBED sdhama.hard.in
vig -d JIBER sdhama.hard.in
vig -d JIBES sdhama.hard.in
vig -d JIFFS sdhama.hard.in
vig -d JIFFY sdhama.hard.in
vig -d JIHAD sdhama.hard.in
vig -d JILLS sdhama.hard.in
vig -d JILTS sdhama.hard.in
vig -d JIMMY sdhama.hard.in
vig -d JIMPY sdhama.hard.in
vig -d JINGO sdhama.hard.in
vig -d JINKS sdhama.hard.in
vig -d JINNI sdhama.hard.in
vig -d JINNS sdhama.hard.in
vig -d JISMS sdhama.hard.in
vig -d JIVED sdhama.hard.in
vig -d JIVER sdhama.hard.in
vig -d JIVES sdhama.hard.in
vig -d JIVEY sdhama.hard.in
vig -d JOCKO sdhama.hard.in
vig -d JOCKS sdhama.hard.in
vig -d JOEYS sdhama.hard.in
vig -d JOHNS sdhama.hard.in
vig -d JOINS sdhama.hard.in
vig -d JOINT sdhama.hard.in
vig -d JOIST sdhama.hard.in
vig -d JOKED sdhama.hard.in
vig -d JOKER sdhama.hard.in
vig -d JOKES sdhama.hard.in
vig -d JOKEY sdhama.hard.in
vig -d JOLES sdhama.hard.in
vig -d JOLLY sdhama.hard.in
vig -d JOLTS sdhama.hard.in
vig -d JOLTY sdhama.hard.in
vig -d JONES sdhama.hard.in
vig -d JORAM sdhama.hard.in
vig -d JORUM sdhama.hard.in
vig -d JOTAS sdhama.hard.in
vig -d JOTTY sdhama.hard.in
vig -d JOUAL sdhama.hard.in
vig -d JOUKS sdhama.hard.in
vig -d JOULE sdhama.hard.in
vig -d JOUST sdhama.hard.in
vig -d JOWAR sdhama.hard.in
vig -d JOWED sdhama.hard.in
vig -d JOWLS sdhama.hard.in
vig -d JOWLY sdhama.hard.in
vig -d JOYED sdhama.hard.in 
